grunt:
    image: digitallyseamless/nodejs-bower-grunt
    command: |
        bash -c "
        set -ex 

        npm install
        bower install
        grunt patch-settings --file dev
        chown -R ${E_UID}: ."
    environment:
        E_UID: 1000
    volumes:
        - .:/data
