app:
    build: .
    command: |
        bash -c "
        ./manage.py collectstatic --noinput
        gunicorn_django  . -b 0:8080"
    links:
        - db
    environment:
        - DJANGO_SETTINGS_MODULE=core.settings

webserver:
    image: nginx
    ports:
        - "80:8080"
    volumes:
        - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
        - app
    volumes_from:
        - app

db:
    image: postgres
