grunt:
    image: digitallyseamless/nodejs-bower-grunt
    command: |
        bash -c "
        set -ex 

        npm install
        bower install
        grunt patch-settings --file dev
        chown -R ${UID}:${UID} ."
    environment:
        E_UID: 1000
        CI: 'true'
    volumes:
        - .:/data
