app:
    build: .
    command: python manage.py runserver 0:8080
    ports:
        - "8080:8080"
    links:
        - db
    environment:
        - DATABASE_URL=postgres://postgres@db:5432/postgres
        - DJANGO_SETTINGS_MODULE=core.dev_settings.dev
    volumes:
        - .:/usr/src/app

db:
    image: postgres
